// Bakes the version and the example config into src/generated.ts so they are compiled in: a standalone
// binary has no package.json or examples/ next to it to read at runtime.
import { readFileSync, writeFileSync } from "node:fs";
const root = new URL("..", import.meta.url);
const pkg = JSON.parse(readFileSync(new URL("package.json", root), "utf8"));
const example = readFileSync(new URL("examples/git-drift.config.example.json", root), "utf8");
writeFileSync(
  new URL("src/generated.ts", root),
  `// Generated by scripts/gen.mjs from package.json and examples/ (run on every build). Do not edit.\n` +
    `export const VERSION = ${JSON.stringify(pkg.version)};\n` +
    `export const EXAMPLE_CONFIG = ${JSON.stringify(example)};\n`,
);
